### ISSUE TITLE
error msg when launching decrypt.py

### ISSUE THREAD

**Issue by syrius01** [tweksteen/jenkins-decrypt#10]
Hi,

I receive the following error msg when trying to decrypt:

python decrypt.py test/master.key test/hudson.util.Secret test/cred1.xml
Traceback (most recent call last):
  File "decrypt.py", line 86, in <module>
    main()
  File "decrypt.py", line 76, in main
    p = base64.decodestring(bytes(password, 'utf-8'))
TypeError: str() takes at most 1 argument (2 given)

Any help would be very appreciated :)

**Comment by bstapes** [comment]
The script is written in Python 3. :)  Try this:

**python3** decrypt.py test/master.key test/hudson.util.Secret test/cred1.xml
