### ISSUE TITLE
Can this script be used for decrypting of user passwords within Jenkins?

### ISSUE THREAD

**Issue by fog1985** [tweksteen/jenkins-decrypt#3]
Password I have is in format as follow:
<passwordHash>#jbcrypt:$2a$10$AW...

And after run of this script it doesn't seem to be working fine:

root@jenkins:~/temp# python3 decrypt.py /var/lib/jenkins/secrets/master.key /var/lib/jenkins/secrets/hudson.util.Secret ./pass.xml 
Traceback (most recent call last):
  File "decrypt.py", line 39, in <module>
    main()
  File "decrypt.py", line 20, in main
    hashed_master_key = sha256(master_key).digest()[:16]
TypeError: Unicode-objects must be encoded before hashing

**Comment by tweksteen** [comment]
I doubt. The magic at the beginning of the hash seems to refer to http://www.mindrot.org/projects/jBCrypt/.      It might worth having a look if John the ripper supports that format.
