### ISSUE TITLE
ValueError: Input strings must be a multiple of 16 in length

### ISSUE THREAD

**Issue by kenorb** [tweksteen/jenkins-decrypt#5]
I've similar issue as in #1, but on Linux and the fix from other issue is already included.

```
$ ./jenkins-decrypt/decrypt.py secrets/master.key secrets/hudson.util.Secret credentials.xml 
Traceback (most recent call last):
  File "./jenkins-decrypt/decrypt.py", line 41, in <module>
    main()
  File "./jenkins-decrypt/decrypt.py", line 35, in main
    x = o.decrypt(p)
  File "/usr/lib64/python2.6/dist-packages/Crypto/Cipher/blockalgo.py", line 295, in decrypt
    return self._cipher.decrypt(ciphertext)
ValueError: Input strings must be a multiple of 16 in length
$ wc -c secrets/master.key secrets/hudson.util.Secret
256 secrets/master.key
272 secrets/hudson.util.Secret
```

The following one-liner works fine:

```
$ python -c 'import sys,hashlib,base64;from Crypto.Cipher import AES;master,secret=AES.new(hashlib.sha256(open("secrets/master.key").read()).digest(),AES.MODE_ECB),open("secrets/hudson.util.Secret").read();x=master.decrypt(secret)[:-16];print(len(x))'
256
```

I'm using Jenkins v2.73.1

**Comment by mciverza** [comment]
+1 same issue for me.
can also run 
python -c 'import sys,hashlib,base64;from Crypto.Cipher import AES;master,secret=AES.new(hashlib.sha256(open("secrets/master.key").read()).digest(),AES.MODE_ECB),open("secrets/hudson.util.Secret").read();x=master.decrypt(secret)[:-16];print(len(x))'

on Ubuntu 16.04, Python 2.7.12
python-pycryptopp                  0.6.0.20120313-1build1 

Jenkins version 2.32.1

**Comment by theblazehen** [comment]
So, this script works on the old encryption scheme. I'll send through a PR that fixes it in a short while

**Comment by theblazehen** [comment]
@kenorb  @mciverza I've fixed it in https://github.com/tweksteen/jenkins-decrypt/pull/6

**Comment by tweksteen** [comment]
Thanks for the report and the pull request. I'll review it this week.
