### ISSUE TITLE
TypeError: Can't convert 'bytes' object to str implicitly

### ISSUE THREAD

**Issue by egr-ext** [tweksteen/jenkins-decrypt#8]
Hi,

Thanks for your script. 
I have Python 3 and pycrypto (2.6.1). I'am trying to move/restore credentials from Jenkins1.6 to a new jenkins2.x instance.
I tried to execute your script but I get this error: 
Traceback (most recent call last):
```
  File "./decrypt.py", line 87, in <module>
    main()
  File "./decrypt.py", line 84, in main
    print(decryptOldPassword(secret,p))
  File "./decrypt.py", line 55, in decryptOldPassword
    return re.findall('(.*)' + MAGIC, x)[0]
TypeError: Can't convert 'bytes' object to str implicitly
```

Do you have any clue ? is there another way to move the credential from a jenkins to another ? Espacially we try to retrieve an android keystore we store on the old jenkins.

Merci, Regards
Eric

**Comment by andrewsowerby** [comment]
I have the same issue:

`$/python3 ./decrypt.py master.key hudson.util.Secret credentials.xml` 
`Traceback (most recent call last):`
  `File "./decrypt.py", line 86, in <module>`
`    main()`
`  File "./decrypt.py", line 83, in main`
`    print(decryptOldPassword(secret,p))`
`  File "./decrypt.py", line 55, in decryptOldPassword`
`    return re.findall('(.*)' + MAGIC, x)[0]`
`TypeError: Can't convert 'bytes' object to str implicitly`

**Comment by andrewsowerby** [comment]
Just got past this issue my installing pip3, and using that to install pycrpto. I already had python3-dev, which included pycrypto, but when I installed pip3 and ran `pip3 install pycrypto` I progressed to the next error ;)
Now I see:
`Fatal Python error: Py_Initialize: Unable to get the locale encoding`
`ImportError: No module named 'encodings'`

I guess I may be missing a few modules...
